# Generated by Django 5.0.6 on 2024-07-12 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ParentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField(help_text='Full Address')),
                ('contact_information', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.BooleanField(default=False, help_text='Is this the current school year?')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField(help_text='Full Address')),
                ('contact_information', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=500)),
                ('color', models.CharField(max_length=20)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.eventcategory')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.gradelevel')),
                ('adviser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projectapp.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lrn', models.CharField(help_text='Learner Reference Number', max_length=20, null=True, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('place_of_birth', models.TextField(help_text='Birth Address')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10)),
                ('address', models.TextField(help_text='Full Address')),
                ('promoted', models.BooleanField(default=False)),
                ('parent_guardians', models.ForeignKey(help_text='List of Parents/Guardians', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectapp.parentguardian')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('refunded', 'Refunded')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('payment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Form137',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('records', models.ManyToManyField(blank=True, to='projectapp.academicrecord')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.school')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projectapp.student')),
            ],
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.student'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectapp.gradelevel')),
            ],
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.subject'),
        ),
        migrations.CreateModel(
            name='StudentYearInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_ave', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tdays_of_classes', models.IntegerField(blank=True, null=True)),
                ('tdays_of_present', models.IntegerField(blank=True, null=True)),
                ('promoted', models.BooleanField(default=False)),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_grade_level', to='projectapp.gradelevel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.school')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.schoolyear')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectapp.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.student')),
                ('to_be_classified', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_grade_level', to='projectapp.gradelevel')),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.teacher')),
            ],
            options={
                'verbose_name': 'Student Year Information',
                'verbose_name_plural': 'Student Year Information',
            },
        ),
        migrations.CreateModel(
            name='TotalGradeSubject',
            fields=[
                ('TGS_ID', models.AutoField(primary_key=True, serialize=False)),
                ('first_grading', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('second_grading', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('third_grading', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fourth_grading', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('FINAL_GRADES', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('PASSED_FAILED', models.CharField(blank=True, max_length=20, null=True)),
                ('STUDENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.student')),
                ('SUBJECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.subject')),
                ('SYI_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.studentyearinfo')),
            ],
            options={
                'verbose_name': 'Total Grade Subject',
                'verbose_name_plural': 'Total Grade Subjects',
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectapp.gradelevel')),
                ('school_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectapp.schoolyear')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectapp.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.student')),
            ],
            options={
                'verbose_name': 'Student Year Information',
                'unique_together': {('student', 'school_year')},
            },
        ),
    ]
