# Generated by Django 5.0.6 on 2024-07-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentgrade',
            options={'verbose_name': 'Student Grade', 'verbose_name_plural': 'Student Grades'},
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='first_grading',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='fourth_grading',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='second_grading',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='third_grading',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
