# Generated by Django 5.0.6 on 2024-07-14 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentGrade',
        ),
    ]
