# Generated by Django 5.0.7 on 2024-07-18 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grade_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectapp.gradelevel'),
        ),
    ]
