# Generated by Django 5.0.6 on 2024-07-14 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_delete_studentgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_grading', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('second_grading', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('third_grading', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fourth_grading', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.studentinfo')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.subject')),
            ],
        ),
    ]
