# Generated by Django 5.0.6 on 2024-07-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_alter_studentgrade_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentgrade',
            options={},
        ),
    ]
