# Generated by Django 5.0.6 on 2024-07-14 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_studentgrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='grade_level',
        ),
    ]
