# Generated by Django 5.0.6 on 2024-07-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_remove_student_grade_level_studentinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolyear',
            name='status',
            field=models.BooleanField(default=False, help_text='Is this the current school year?'),
        ),
    ]
