# Generated by Django 5.0.6 on 2024-07-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_schoolyear_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentguardian',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
