# Generated by Django 5.0.6 on 2024-07-08 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0007_alter_student_middle_name_alter_teacher_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='projectapp.teacher'),
        ),
    ]
