# Generated by Django 5.0.6 on 2024-07-08 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0008_teacher_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='teacher',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectapp.teacher'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='position',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
