# Generated by Django 5.0.6 on 2024-07-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0009_remove_teacher_supervisor_teacher_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='position',
        ),
    ]
